import React, { useMemo, useState } from 'react';
import { mockUsers } from '../../mock/mockUsers';
import { mockProducts } from '../../mock/mockProducts';
import { mockOrders } from '../../mock/mockOrders';
import { mockCategories } from '../../mock/mockCategories';
import { formatCurrency } from '../../utils/helpers';
import './ManagementPage.css';

const source = { users: mockUsers, categories: mockCategories, orders: mockOrders, payments: mockOrders, reports: mockOrders };
const titles = { users: 'User Management', products: 'Product Management', categories: 'Categories', orders: 'Order Management', payments: 'Payments', reports: 'Reports', settings: 'Settings' };
const emptyProduct = { name: '', sku: '', category: 'Electronics', price: '', discount: '', stock: '', description: '', image: '' };

const ProductEditor = ({ product, onClose, onSave }) => {
  const [form, setForm] = useState(product || emptyProduct);
  const [preview, setPreview] = useState(product?.image || '');
  const update = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  const upload = (event) => { const file = event.target.files?.[0]; if (file) setPreview(URL.createObjectURL(file)); };
  const save = (event) => { event.preventDefault(); onSave({ ...form, id: form.id || Date.now(), image: preview || 'https://placehold.co/400x400?text=Product', price: Number(form.price), stock: Number(form.stock), discount: Number(form.discount || 0) }); };
  return <div className="editor-backdrop" role="dialog" aria-modal="true"><form className="product-editor" onSubmit={save}><div className="editor-title"><h2>{product ? 'Edit product' : 'Add product'}</h2><button type="button" onClick={onClose}>×</button></div><div className="product-form-grid"><label>Product name<input name="name" value={form.name} onChange={update} required /></label><label>SKU<input name="sku" value={form.sku || ''} onChange={update} required /></label><label>Category<select name="category" value={form.category} onChange={update}><option>Electronics</option><option>Fashion</option><option>Home</option><option>Sports</option><option>Wearables</option></select></label><label>Price<input name="price" type="number" min="0" step="0.01" value={form.price} onChange={update} required /></label><label>Discount %<input name="discount" type="number" min="0" max="100" value={form.discount} onChange={update} /></label><label>Stock<input name="stock" type="number" min="0" value={form.stock} onChange={update} required /></label><label className="form-full">Description<textarea name="description" value={form.description || ''} onChange={update} rows="3" /></label></div><div className="image-upload"><div>{preview ? <img src={preview} alt="Product preview" /> : <span>No image selected</span>}</div><label>Upload product image<input type="file" accept="image/*" onChange={upload} /></label>{preview && <button type="button" className="remove-image" onClick={() => setPreview('')}>Delete image</button>}</div><div className="editor-actions"><button type="button" onClick={onClose}>Cancel</button><button className="add-button" type="submit">Save product</button></div></form></div>;
};

const AdminManagementPage = ({ type }) => {
  const [products, setProducts] = useState(mockProducts);
  const [query, setQuery] = useState(''); const [filter, setFilter] = useState('all'); const [page, setPage] = useState(1); const [message, setMessage] = useState(''); const [editing, setEditing] = useState(null); const [showEditor, setShowEditor] = useState(false);
  const data = type === 'products' ? products : source[type] || [];
  const rows = useMemo(() => data.filter((item) => JSON.stringify(item).toLowerCase().includes(query.toLowerCase()) && (filter === 'all' || item.status === filter || item.category === filter || item.paymentStatus === filter)), [data, query, filter]);
  const visible = rows.slice((page - 1) * 5, page * 5);
  const saveProduct = (product) => { setProducts((current) => current.some((item) => item.id === product.id) ? current.map((item) => item.id === product.id ? { ...item, ...product } : item) : [{ ...product, rating: 0, reviews: 0, brand: 'ShopSphere' }, ...current]); setShowEditor(false); setEditing(null); setMessage(`Product ${product.name} saved.`); };
  const deleteProduct = (id) => { setProducts((current) => current.filter((item) => item.id !== id)); setMessage('Product deleted.'); };
  const changeOrderStatus = (order, status) => { order.status = status; setMessage(`${order.id} updated to ${status.replaceAll('_', ' ')}.`); };
  if (type === 'settings') return <section className="management-page"><h1>Admin Settings</h1><div className="settings-card"><h2>Store settings</h2><label>Store name<input defaultValue="ShopSphere" /></label><label>Support email<input defaultValue="support@shopsphere.demo" /></label><button onClick={() => setMessage('Settings saved (demo).')}>Save settings</button>{message && <p>{message}</p>}</div></section>;
  const headers = type === 'users' ? ['Profile', 'Name', 'Email', 'Mobile', 'Role', 'Status', 'Created', 'Actions'] : type === 'products' ? ['Image', 'Product', 'SKU', 'Category', 'Price', 'Discount', 'Stock', 'Actions'] : type === 'orders' ? ['Order', 'Customer', 'Total', 'Status', 'Payment', 'Date', 'Actions'] : type === 'payments' ? ['Order', 'Method', 'Amount', 'Status', 'Date', 'Actions'] : type === 'categories' ? ['Category', 'Description', 'Products', 'Actions'] : ['Order', 'Revenue', 'Status', 'Date', 'Actions'];
  const cells = (item) => {
    if (type === 'users') return <><td><img className="table-avatar" src={item.avatar} alt="" /></td><td>{item.name}</td><td>{item.email}</td><td>{item.mobile}</td><td>{item.role}</td><td><span className={`table-status ${item.status}`}>{item.status}</span></td><td>{item.createdDate}</td></>;
    if (type === 'products') return <><td><img className="table-product" src={item.image} alt="" /></td><td>{item.name}</td><td>{item.sku || `SKU-${item.id}`}</td><td>{item.category}</td><td>{formatCurrency(item.price)}</td><td>{item.discount || 0}%</td><td>{item.stock ?? 0}</td></>;
    if (type === 'orders') return <><td>{item.id}</td><td>{item.shippingAddress?.fullName || item.shippingAddress?.name}</td><td>{formatCurrency(item.total)}</td><td><select className="status-select" value={item.status} onChange={(event) => changeOrderStatus(item, event.target.value)}>{['pending', 'confirmed', 'processing', 'shipped', 'out_for_delivery', 'delivered', 'cancelled'].map((status) => <option key={status}>{status}</option>)}</select></td><td>{item.paymentStatus}</td><td>{item.orderDate}</td></>;
    if (type === 'payments') return <><td>{item.id}</td><td>{item.paymentMethod}</td><td>{formatCurrency(item.total)}</td><td><span className={`table-status ${item.paymentStatus}`}>{item.paymentStatus}</span></td><td>{item.orderDate}</td></>;
    if (type === 'categories') return <><td>{item.name}</td><td>{item.description || 'Product category'}</td><td>{item.productCount || 0}</td></>;
    return <><td>{item.id}</td><td>{formatCurrency(item.total)}</td><td>{item.status}</td><td>{item.orderDate}</td></>;
  };
  return <section className="management-page"><div className="management-heading"><div><h1>{titles[type]}</h1><p>Manage storefront data with demo frontend controls.</p></div><div><button onClick={() => setMessage('Excel export prepared (demo).')}>Export Excel</button><button onClick={() => setMessage('PDF download prepared (demo).')}>Download PDF</button><button className="add-button" onClick={() => type === 'products' ? setShowEditor(true) : setMessage(`Add ${type.slice(0, -1)} form opened (demo).`)}>Add {type.slice(0, -1)}</button></div></div>{message && <p className="management-message">{message}</p>}<div className="table-tools"><input placeholder="Search..." value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} /><select value={filter} onChange={(event) => { setFilter(event.target.value); setPage(1); }}><option value="all">All</option><option value="active">Active</option><option value="processing">Processing</option><option value="delivered">Delivered</option><option value="completed">Completed</option></select></div><div className="management-table"><table><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{visible.map((item) => <tr key={item.id}>{cells(item)}<td className="table-actions"><button onClick={() => setMessage(`Viewing ${item.name || item.id} details (demo).`)}>View</button><button onClick={() => type === 'products' ? (setEditing(item), setShowEditor(true)) : setMessage(`Editing ${item.name || item.id} (demo).`)}>Edit</button><button onClick={() => type === 'products' ? deleteProduct(item.id) : setMessage(`${item.name || item.id} updated (demo).`)}>{type === 'users' ? 'Toggle' : 'Delete'}</button></td></tr>)}</tbody></table></div><div className="pagination"><button disabled={page === 1} onClick={() => setPage(page - 1)}>Previous</button><span>Page {page} of {Math.max(1, Math.ceil(rows.length / 5))}</span><button disabled={page * 5 >= rows.length} onClick={() => setPage(page + 1)}>Next</button></div>{showEditor && <ProductEditor product={editing} onClose={() => { setShowEditor(false); setEditing(null); }} onSave={saveProduct} />}</section>;
};
export default AdminManagementPage;
